### ISSUE TITLE
bristol dependencies (xproto)

### ISSUE THREAD

**Issue by norayr** [audiodef/gentoostudio#2]
hello, media-sound/bristol [requires x11-proto/xproto](https://github.com/audiodef/gentoostudio/blob/master/media-sound/bristol/bristol-0.60.11.ebuild#L25), but that dependency have been removed in gentoo.
as far as i understand, it have been merged in to x11-base/xcb-proto.

thank you.

**Comment by audiodef** [comment]
It's in portage now, and the devs there have taken care of that dependency.
